# Generated by Django 4.2.13 on 2026-04-23 14:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_islands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataisland',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataisland',
            name='pii_policy',
            field=models.CharField(choices=[('allow', 'Allow All'), ('hide', 'Exclude PII Columns'), ('encrypt', 'MD5 Hash PII Columns')], default='allow', max_length=20),
        ),
        migrations.AddField(
            model_name='dataisland',
            name='refresh_strategy',
            field=models.CharField(choices=[('full', 'Full Refresh'), ('incremental', 'Incremental')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='dataisland',
            name='refresh_type',
            field=models.CharField(choices=[('static', 'Static (one-time)'), ('scheduled', 'Scheduled')], default='static', max_length=20),
        ),
        migrations.AddField(
            model_name='dataisland',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('cron', 'Cron Expression'), ('frequency', 'Frequency')], default='cron', max_length=20),
        ),
        migrations.AddField(
            model_name='dataisland',
            name='schedule_value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dataisland',
            name='refresh_mode',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataisland',
            name='sql_query',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataisland',
            name='view_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='DataIslandTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=255)),
                ('view_name', models.CharField(max_length=64, unique=True)),
                ('sql_query', models.TextField()),
                ('time_column', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('error', 'Error'), ('stale', 'Stale')], default='draft', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='island_tables', to='data_islands.dataisland')),
            ],
            options={
                'ordering': ['table_name'],
                'unique_together': {('island', 'table_name')},
            },
        ),
    ]
