"""
Central email dispatch for Data Governance Project.

All outbound email goes through this module so that the email server is
configured in exactly one place (core/settings.py → EMAIL_* env vars).
"""

import logging

from django.conf import settings
from django.core.mail import send_mail as _send_mail, EmailMessage

logger = logging.getLogger(__name__)


def _send(subject: str, body: str, recipient_list: list[str]) -> bool:
    """Low-level wrapper. Returns True on success, False on failure (logged)."""
    try:
        _send_mail(
            subject=subject,
            message=body,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=recipient_list,
            fail_silently=False,
        )
        logger.info("[email] Sent '%s' to %s", subject, ", ".join(recipient_list))
        return True
    except Exception as exc:
        logger.warning("[email] Failed to send '%s' to %s: %s", subject, ", ".join(recipient_list), exc)
        return False


def send_db_credentials(
    recipient: str,
    *,
    name: str,
    username: str,
    password: str,
    privilege_level: str,
) -> bool:
    """Email generated database credentials to a new IAM user."""
    body = (
        f"Hello {name or username},\n\n"
        "A database account has been created for you in Data Governance Project.\n\n"
        f"  Username : {username}\n"
        f"  Password : {password}\n"
        f"  Access   : {privilege_level.replace('_', ' ').title()}\n\n"
        "Please change your password after your first login.\n\n"
        "— Data Governance Project"
    )
    return _send(
        subject="Your Data Governance Project database credentials",
        body=body,
        recipient_list=[recipient],
    )


def send_access_report(
    recipient_list: list[str],
    *,
    subject_name: str,
    report: dict,
) -> bool:
    """Email a DPDPA Part A access report to the data subject and any extra recipients."""
    lines = [
        f"Dear {subject_name},",
        "",
        "Please find below a summary of the personal data processed about you.",
        "",
        f"Summary: {report.get('summary', '')}",
        "",
        "Data Inventory:",
    ]
    for entry in report.get("data_inventory", []):
        lines.append(f"  Table      : {entry['table']}")
        pii = ", ".join(entry.get("pii_columns", [])) or "—"
        cats = ", ".join(entry.get("data_categories", [])) or "—"
        lines.append(f"  PII columns: {pii}")
        lines.append(f"  Categories : {cats}")
        if entry.get("via"):
            lines.append(f"  Via        : {entry['via']}")
        lines.append("")
    lines += [
        f"Legal basis: {report.get('legal_basis', '')}",
        "",
        report.get("notes", ""),
        "",
        "— Data Governance Project",
    ]
    return _send(
        subject="Your Data Access Report — Data Governance Project",
        body="\n".join(lines),
        recipient_list=recipient_list,
    )


# Contact details surfaced in visitor-facing email — mirrors the "Reach Us"
# dialog in the frontend (components/ReachUsButton.jsx). Sourced from the
# TEAM_CONTACTS env var (see core/settings.py); empty by default.
_TEAM_CONTACTS = settings.TEAM_CONTACTS


# Standard closing note appended to every Query Editor results mail. It always
# goes out (regardless of any user-supplied note) and leads into the team
# contact block below it.
QUERY_RESULTS_STANDARD_NOTE = (
    "This email was generated by The Data Governance Project on behalf of a demo "
    "session. To connect with us or to book a meeting, reach out using the "
    "contact details below:"
)


def send_query_results(
    recipient_list: list[str],
    *,
    query_name: str,
    message: str = "",
    csv_bytes: bytes | None = None,
    csv_name: str = "results.csv",
    row_count: int | None = None,
    target: str = "",
) -> bool:
    """
    Email the result set of a saved query to `recipient_list`.

    Sent from settings.CONTACT_EMAIL (hello@datagovernanceproject.com) so replies
    reach the team. `message` is an optional user note placed above the standard
    note; QUERY_RESULTS_STANDARD_NOTE + team contacts are always included.
    Results ride along as a CSV attachment.
    """
    lines = []
    if message and message.strip():
        lines += [message.strip(), ""]
    if row_count is not None:
        detail = f"Attached: {row_count} row(s) from “{query_name}”"
        if target:
            detail += f" ({target})"
        lines += [detail + ".", ""]
    lines += [QUERY_RESULTS_STANDARD_NOTE, ""]
    if _TEAM_CONTACTS:
        lines += [_TEAM_CONTACTS, ""]
    lines += ["— The Data Governance Project"]

    try:
        email = EmailMessage(
            subject=f"[DGP] {query_name} — data export",
            body="\n".join(lines),
            from_email=settings.CONTACT_EMAIL,
            to=recipient_list,
            reply_to=[settings.CONTACT_EMAIL],
        )
        if csv_bytes is not None:
            email.attach(csv_name, csv_bytes, "text/csv")
        email.send(fail_silently=False)
        logger.info("[email] Query results '%s' sent to %s", query_name, ", ".join(recipient_list))
        return True
    except Exception as exc:
        logger.warning("[email] Query results '%s' failed for %s: %s", query_name, ", ".join(recipient_list), exc)
        return False
