# Generated by Django 5.2.12 on 2026-04-02 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('db_type', models.CharField(choices=[('postgresql', 'Postgresql'), ('mysql', 'Mysql'), ('sqlite', 'Sqlite'), ('bigquery', 'Bigquery'), ('snowflake', 'Snowflake')], max_length=50)),
                ('_credentials_encrypted', models.BinaryField(db_column='credentials_encrypted')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('error', 'Error')], default='pending', max_length=20)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('business_context', models.TextField(blank=True, help_text='Describe the business domain so the AI produces richer descriptions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
