# Generated by Django 4.2.13 on 2026-06-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_csv_file_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='csv_file',
        ),
        migrations.AlterField(
            model_name='datasource',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'Mysql'), ('postgresql', 'Postgresql')], max_length=50),
        ),
    ]
