# Generated by Django 4.2.13 on 2026-04-16 15:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ai_provider', models.CharField(blank=True, max_length=50)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('tables_processed', models.IntegerField(default=0)),
                ('tables_total', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_runs', to='datasources.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableCatalogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(blank=True, max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=512)),
                ('raw_schema', models.TextField(default='{}')),
                ('ai_description', models.TextField(blank=True)),
                ('ai_business_purpose', models.TextField(blank=True)),
                ('ai_domain', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('business_purpose', models.TextField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('tags', models.TextField(blank=True, default='[]')),
                ('row_count_estimate', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_catalogues', to='datasources.datasource')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='catalogue.cataloguerun')),
            ],
            options={
                'ordering': ['full_name'],
                'unique_together': {('run', 'full_name')},
            },
        ),
        migrations.CreateModel(
            name='ColumnCatalogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=100)),
                ('nullable', models.BooleanField(default=True)),
                ('is_primary_key', models.BooleanField(default=False)),
                ('is_foreign_key', models.BooleanField(default=False)),
                ('foreign_key_references', models.TextField(blank=True, null=True)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('native_comment', models.TextField(blank=True, null=True)),
                ('ai_description', models.TextField(blank=True)),
                ('ai_business_name', models.CharField(blank=True, max_length=255)),
                ('ai_data_category', models.CharField(choices=[('identifier', 'Identifier'), ('timestamp', 'Timestamp'), ('metric', 'Metric'), ('dimension', 'Dimension'), ('flag', 'Flag / Boolean'), ('text', 'Free Text'), ('json', 'JSON / Semi-Structured'), ('other', 'Other')], default='other', max_length=50)),
                ('ai_pii_likelihood', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='none', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('data_category', models.CharField(blank=True, choices=[('identifier', 'Identifier'), ('timestamp', 'Timestamp'), ('metric', 'Metric'), ('dimension', 'Dimension'), ('flag', 'Flag / Boolean'), ('text', 'Free Text'), ('json', 'JSON / Semi-Structured'), ('other', 'Other')], max_length=50)),
                ('pii_likelihood', models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('is_pii_confirmed', models.BooleanField(default=False)),
                ('ordinal_position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='catalogue.tablecatalogue')),
            ],
            options={
                'ordering': ['ordinal_position'],
                'unique_together': {('table', 'column_name')},
            },
        ),
    ]
