# Generated by Django 5.2.12 on 2026-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_uploads/'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='db_type',
            field=models.CharField(choices=[('postgresql', 'Postgresql'), ('mysql', 'Mysql'), ('sqlite', 'Sqlite'), ('bigquery', 'Bigquery'), ('snowflake', 'Snowflake'), ('csv', 'Csv')], max_length=50),
        ),
    ]
