# Generated by Django 4.2.13 on 2026-09-08 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasources', '0003_remove_datasource_csv_file_alter_datasource_db_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sql_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_queries', to=settings.AUTH_USER_MODEL)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to='datasources.datasource')),
            ],
            options={
                'verbose_name_plural': 'Saved queries',
                'ordering': ['-updated_at'],
            },
        ),
    ]
