# Generated by Django 4.2.13 on 2026-09-09 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0003_remove_datasource_csv_file_alter_datasource_db_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queryeditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cadence_type', models.CharField(choices=[('cron', 'Cron Expression'), ('frequency', 'Frequency')], default='frequency', max_length=20)),
                ('cadence_value', models.CharField(max_length=200)),
                ('write_mode', models.CharField(choices=[('replace', 'Replace'), ('append', 'Append')], default='replace', max_length=20)),
                ('target_schema', models.CharField(default='schedules', max_length=64)),
                ('target_table', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('last_row_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_schedules', to=settings.AUTH_USER_MODEL)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_schedules', to='datasources.datasource')),
                ('saved_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='queryeditor.savedquery')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('datasource', 'target_schema', 'target_table')},
            },
        ),
        migrations.CreateModel(
            name='QueryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('write_mode', models.CharField(blank=True, max_length=20)),
                ('target', models.CharField(blank=True, max_length=256)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('elapsed_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('schedule', 'Schedule'), ('manual', 'Manual')], default='schedule', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='queryeditor.queryschedule')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
