# Generated by Django 4.2.13 on 2026-09-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryeditor', '0002_queryschedule_queryrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryrun',
            name='email_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='queryschedule',
            name='email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queryschedule',
            name='email_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='queryschedule',
            name='email_recipients',
            field=models.TextField(blank=True),
        ),
    ]
