# Generated by Django 4.2.13 on 2026-06-17 05:08

import catalogue.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0003_remove_datasource_csv_file_alter_datasource_db_type'),
        ('catalogue', '0002_tablecatalogue_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columncatalogue',
            name='foreign_key_references',
            field=catalogue.models.JSONTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablecatalogue',
            name='raw_schema',
            field=catalogue.models.JSONTextField(default=dict),
        ),
        migrations.AlterField(
            model_name='tablecatalogue',
            name='tags',
            field=catalogue.models.JSONTextField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='RelationshipRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_table', models.CharField(max_length=255)),
                ('from_column', models.CharField(max_length=255)),
                ('to_table', models.CharField(max_length=255)),
                ('to_column', models.CharField(max_length=255)),
                ('cardinality', models.CharField(choices=[('many-to-one', 'Many to One'), ('one-to-many', 'One to Many'), ('one-to-one', 'One to One'), ('many-to-many', 'Many to Many')], default='many-to-one', max_length=20)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('is_auto', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('fk', 'Foreign Key Constraint'), ('name', 'Name-based Detection'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_rules', to='datasources.datasource')),
            ],
            options={
                'ordering': ['from_table', 'from_column'],
                'unique_together': {('datasource', 'from_table', 'from_column', 'to_table', 'to_column')},
            },
        ),
    ]
