# Generated by Django 4.2.13 on 2026-04-11 16:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasources', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIsland',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('view_name', models.CharField(max_length=255)),
                ('sql_query', models.TextField()),
                ('source_tables', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('error', 'Error'), ('stale', 'Stale')], default='draft', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_mode', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('refresh_schedule', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_islands', to='datasources.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataIslandAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.CharField(blank=True, max_length=255)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='data_islands.dataisland')),
            ],
            options={
                'ordering': ['granted_at'],
                'unique_together': {('island', 'email')},
            },
        ),
    ]
