# Generated by Django 4.2.13 on 2026-04-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_islands', '0002_dataisland_next_run_at_dataisland_pii_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataislandtable',
            name='view_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
