# Generated by Django 4.2.13 on 2026-05-30 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_csv_file_field'),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='databaseuser',
            unique_together={('username', 'datasource')},
        ),
    ]
