# Generated by Django 4.2.13 on 2026-06-18 03:38

import catalogue.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasources', '0003_remove_datasource_csv_file_alter_datasource_db_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErasureAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=100)),
                ('data_principal_id', models.CharField(max_length=500)),
                ('identifier_field', models.CharField(max_length=512)),
                ('identifier_values', catalogue.models.JSONTextField(default=list)),
                ('tables_affected', catalogue.models.JSONTextField(default=list)),
                ('rows_deleted', models.IntegerField()),
                ('approver_identity', models.CharField(max_length=500)),
                ('approved_at', models.DateTimeField()),
                ('executed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErasureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_principal_id', models.CharField(max_length=500)),
                ('identifier_table', models.CharField(max_length=255)),
                ('identifier_column', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('text', 'Text (comma/newline-separated)'), ('csv', 'CSV Upload'), ('table', 'From Connected Table')], max_length=10)),
                ('input_raw', models.TextField()),
                ('input_resolved', catalogue.models.JSONTextField(default=list)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Plan Ready'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erasure_requests', to='datasources.datasource')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErasurePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_data', catalogue.models.JSONTextField(default=list)),
                ('total_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='compliance.erasurerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ErasureApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmation_phrase', models.CharField(max_length=500)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_approvals', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='compliance.erasurerequest')),
            ],
        ),
    ]
