# Generated by Django 4.2.13 on 2026-06-26 05:28

import catalogue.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0003_remove_datasource_csv_file_alter_datasource_db_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.CharField(max_length=500)),
                ('subject_email', models.EmailField(max_length=500)),
                ('additional_emails', catalogue.models.JSONTextField(default=list)),
                ('identifier_table', models.CharField(max_length=255)),
                ('identifier_column', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('discovering', 'Discovering Data'), ('discovered', 'Data Discovered'), ('report_ready', 'Report Ready'), ('sent', 'Report Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='datasources.datasource')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessDiscovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discovery_data', catalogue.models.JSONTextField(default=list)),
                ('total_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery', to='compliance.accessrequest')),
            ],
        ),
    ]
