# Generated by Django 4.2.13 on 2026-06-04 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iam', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='db_user',
        ),
        migrations.AddField(
            model_name='databaseuser',
            name='platform_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
